# Generated by Django 4.0.4 on 2022-12-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={},
        ),
    ]
