# Generated by Django 4.0.4 on 2022-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_consumer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('discrip', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
