# Generated by Django 4.0.4 on 2022-12-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.consumer'),
        ),
    ]
