# Generated by Django 4.0.4 on 2022-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_cart_user_remove_order_user_cart_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='no_of_items',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
