# Generated by Django 4.0.4 on 2022-12-13 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_shippingaddress_remove_order_cart_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerHistory',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.cart')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            bases=('customer.cart',),
        ),
    ]
