# Generated by Django 4.0.4 on 2022-12-13 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_buyerhistory_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerhistory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 17, 52, 20, 787169, tzinfo=utc)),
        ),
    ]
