# Generated by Django 4.0.4 on 2022-12-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_buyerhistory_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerhistory',
            name='created_date',
        ),
    ]
