# Generated by Django 4.0.4 on 2022-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_remove_buyerhistory_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerHistory',
        ),
    ]
