# Generated by Django 4.0.4 on 2022-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_buyerhistory_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.consumer'),
        ),
    ]
